### ISSUE TITLE
wio.yml updated with garbage

### ISSUE THREAD

**Issue by Mogball** [wio/wio#12]
Whenever wio regenerates wio.yml all the garbage comments explaining how it works are regenerated. Also wio always generates the example files output.h, output.cpp, and the tests/main.cpp. These should ONLY be optional like with a --example flag when creating. Otherwise it should generate a blank project.

The information should be in a README or wiki

**Comment by dhillondeep** [comment]
Okay, I will make the example files optional. Fair point to add a flag for people who want an example. In terms of comments, I will make it so that it generates these comments the first time and after that, with an update, it won't generate them anymore
