### ISSUE TITLE
Print to stderr on error

### ISSUE THREAD

**Issue by dshynkev** [wio/wio#20]
Currently, `wio ... > /dev/null` silences all output, including error messages. This should not be the case; error messages should be printed to `stderr`.

**Comment by dshynkev** [comment]
Clarification: compilation errors, which are probably most common, do get printed to `stderr` by the toolchain, but, for example, `wio build` in an empty directory prints `Not a valid wio project: wio.yml file missing` to `stdout`.

**Comment by dhillondeep** [comment]
This is a valid point. I will add that for the next build. Everything warning and error-related should be printed to `stderr`
