### ISSUE TITLE
Remove npm dependency

### ISSUE THREAD

**Issue by dhillondeep** [wio/wio#21]
At the moment `wio` uses the system call to execute `npm` tool and uses that to pull all the dependencies. We can implement this ourselves by using https://registry.npmjs.org/. This provides access to all the package metadata and links to tarballs

**Comment by dhillondeep** [comment]
#49 #50 #51 #52 #53 #56 are implementing this feature. So far install is working but the idea is to remove npm dependency fully

**Comment by Mogball** [comment]
#80
