### ISSUE TITLE
Please stop breaking my builds

### ISSUE THREAD

**Issue by Mogball** [wio/wio#27]
@dhillondeep I've said this a few times but wio must be backwards compatible

I don't want to reconfigure all my builds when wio updates

Projects under older style configs simply shouldn't have access to newer features, and that's fine

**Comment by Mogball** [comment]
I mean you don't see `cmake` breaking everyone's builds whenever it updates

**Comment by dhillondeep** [comment]
wio is still technically in beta so we are testing new features. But good point we can add version to wio.yml and based on that provide new features or not
