### ISSUE TITLE
Desktop Build

### ISSUE THREAD

**Issue by Mogball** [wio/wio#34]
I'm pretty sure it just involves changing the toolchain path and adding `add_executable` instead of that firmware stuff

**Comment by dhillondeep** [comment]
wait till I finish the current rewrite and then I will tell you what to change. New rewrite makes it more modular

**Comment by Mogball** [comment]
ye no worries just looking through the code base

**Comment by dhillondeep** [comment]
We can have `desktop` as platform and then `c` and `c++` as frameworks

**Comment by dhillondeep** [comment]
This is implemented
