### ISSUE TITLE
cmake paths on windows are incorrect

### ISSUE THREAD

**Issue by Mogball** [wio/wio#65]
`io.Sep` is backslash on windows but cmake needs them to be escaped

**Comment by dhillondeep** [comment]
we can just use `/` everywhere. If not everywhere then atleast every cmake path can be converted into `/` using `filepath.ToSlash`

**Comment by Mogball** [comment]
yeah I think there's a missing `filepath.ToSlash` call somewhere

**Comment by Mogball** [comment]
closed in #71
